## Introduction to arrays and linear algebra
The code cells in this notebook will be filled in live in class and then saved and committed to the course repo as is. This way you have a record of what was covered in class.

* let's start with a list or two of length 3

In [4]:
a = [ 1, 2, 3] 
b = [4, 5, 6]

In [5]:
print a, b

[1, 2, 3] [4, 5, 6]


In [6]:
a+b

[1, 2, 3, 4, 5, 6]

* create some vectors using numpy, and try operations

In [8]:
import numpy as np

In [11]:
u = np.array(a)
v = np.array(b)

In [17]:
u*v

array([ 4, 10, 18])

In [22]:
def dot_prod(u,v):
    '''
    vector product
    
    input: two vectors of equal lenght
    output: scalar 
        
    '''
    if len(u) is not len(v): 
        print "error"
    uv_prod = 0
    for i in range(len(u)):
        uv_prod += u[i]*v[i]
    return uv_prod

print uv_prod

32


In [25]:
import my_lib


In [26]:
my_lib.dot_prod(u,v)

32

* array creation
    - zeros
    - `range` -> array, `arange`
    - `np.arange(10), np.arange(2, 10, dtype=np.float), np.arange(2, 3, 0.1)`
    - `linspace`
    - special function: `np.random.randn(10)`

In [32]:
x=np.linspace(1,2,10)

In [34]:
np.sin(x)

array([ 0.84147098,  0.8961922 ,  0.93986069,  0.9719379 ,  0.99202822,
        0.99988386,  0.99540796,  0.9786557 ,  0.94983371,  0.90929743])

In [41]:
r=np.arange(4.9,dtype='float')

* properties of arrays, length, dtype
* splicing: take only parts of your arrays
    - range
    - index array
    - negative indices

In [48]:
r = 2.*r
r

array([  0.,   4.,   8.,  12.,  16.])

In [49]:
r[0:2]

array([ 0.,  4.])

In [50]:
r_ind=[1,3]

In [51]:
r[r_ind]

array([  4.,  12.])

In [52]:
r[-2]

12.0

* combining arrays into arrays (2D data structures)
    - looks like a matrix
    - indexing, this is a 2x3 matrix

In [54]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([1,2,1])

In [58]:
A=np.array([a1,a2,a3])

In [59]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 1]])

In [61]:
A[1]

array([4, 5, 6])

* creating a matrix - vector operation
    - create vector `v` of length 3
    - write a function that receives a vector $\vec{v}$ and matrix $\bf{A}$ and returns the vector $\vec{u} = {\bf A} \cdot \vec{v}$

***Challenge: *** submit your code here ....

In [ ]:
# your code: